version: "3.8"

services:
  app:
    build:
      context: ./app
    container_name: fastapi_app
    ports:
      - "8000:80"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Utilise la variable d'environnement pour le root password
      MYSQL_USER: ${MYSQL_USER} # Utilise la variable d'environnement pour l'utilisateur
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # Utilise la variable d'environnement pour le mot de passe
      MYSQL_DATABASE: ${MYSQL_DATABASE} # Utilise la variable d'environnement pour la base de données
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
