apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: <base64_encoded_password>
  MYSQL_USER: <base64_encoded_user>
  MYSQL_PASSWORD: <base64_encoded_password>
  MYSQL_DATABASE: <base64_encoded_database>
